# GitHub Sponsors funding file
# This file is used to display sponsor information on the repository

# GitHub Sponsors
# github: [username]

# Ko-fi
# ko_fi: username

# Patreon
# patreon: username

# Open Collective
# open_collective: othello-ios

# Custom links
# custom: ['https://paypal.me/username', 'https://buy-me-a-coffee.com/username']

# Note: Uncomment and update the above lines when ready to accept sponsorship
# For now, this is a placeholder to prepare for future funding options